// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFzscnh4s4BQdzNs4aBKoJ8tqpG4BlXNY',
    appId: '1:146685693279:web:71840f94b14760cc83baea',
    messagingSenderId: '146685693279',
    projectId: 'resume-tailor-e999d',
    authDomain: 'resume-tailor-e999d.firebaseapp.com',
    storageBucket: 'resume-tailor-e999d.firebasestorage.app',
    measurementId: 'G-P3VCZNSTD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwV5ck-Jos3iuCghMvbmig9NsJz_whKPc',
    appId: '1:146685693279:android:55e6e588afb4193b83baea',
    messagingSenderId: '146685693279',
    projectId: 'resume-tailor-e999d',
    storageBucket: 'resume-tailor-e999d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKbpBWq2WnuX7jhDNb9YZzVgwFaCLdVI',
    appId: '1:146685693279:ios:4ba1691e4e9f508983baea',
    messagingSenderId: '146685693279',
    projectId: 'resume-tailor-e999d',
    storageBucket: 'resume-tailor-e999d.firebasestorage.app',
    iosBundleId: 'com.tailor.resume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfKbpBWq2WnuX7jhDNb9YZzVgwFaCLdVI',
    appId: '1:146685693279:ios:46a4ef4f9ec6b05f83baea',
    messagingSenderId: '146685693279',
    projectId: 'resume-tailor-e999d',
    storageBucket: 'resume-tailor-e999d.firebasestorage.app',
    iosBundleId: 'com.example.resumeTailor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFzscnh4s4BQdzNs4aBKoJ8tqpG4BlXNY',
    appId: '1:146685693279:web:4c70304a48c808f483baea',
    messagingSenderId: '146685693279',
    projectId: 'resume-tailor-e999d',
    authDomain: 'resume-tailor-e999d.firebaseapp.com',
    storageBucket: 'resume-tailor-e999d.firebasestorage.app',
    measurementId: 'G-CY8Z9Z44XB',
  );
}
